### ISSUE TITLE
Fatal error: Class 'Imagine\Image\Color

### ISSUE THREAD

**Issue by phpstudyone** [AlloVince/EvaThumber#19]
Fatal error: Class 'Imagine\Image\Color' not found in C:\wamp\www\source\src\EvaThumber\Thumber.php on line 704

当开启文字水印的时候 会报错

**Comment by l764191074** [comment]
我也出现了这个问题,请问如何解决的

**Comment by phpstudyone** [comment]
> 我也出现了这个问题,请问如何解决的

额,年代太久远了, 当初记得是改了里面很多代码才让他正常跑起来的.

换个软件吧, 直接给服务器安装 `convert` , 然后定时任务处理吧.
