### ISSUE TITLE
source_path地址能否兼容EvaThumber外路径和其他网址的图片？

### ISSUE THREAD

**Issue by xuzeyu** [AlloVince/EvaThumber#20]
config.local.php内source_path参数，填写的是当前EvaThumber下路径。
能否兼容：
1.填写EvaThumber外路径，例如其他项目project下的upload路径？
2.其他网址的图片，而不单单本地的图片。例如百度的图片，通过请求获取图片处理以后返回图片？

**Comment by rainforyou** [comment]
source_path  不是填写的  __DIR__    吗？可以自定义的，你试试
第2个问题是本地化问题吧
